### PR TITLE
v0.2.4

### PR DESCRIPTION
**Pull request by themightychris**
This release will consist of simplifications to the rendering pipeline of both the teacher dashboard and student dashboard that lay the groundwork for correct delete and level handling, but it will not yet make any changes to the database or UI.

### CODE REVIEW

**Comment by themightychris** [comment]
I'm finished working on the student dashboard for this release and I've pulled+built the changes so far to http://rc.cbl.v1.slate.is/  so the student dashboard can be tested.

I'm working on similar changes to the teacher dashboard now that will be added to this version before it is merged

**Comment by jcunn302** [comment]
Looks good to me @themightychris

**Comment by themightychris** [comment]
@jcunn302 teacher dashboard is done internal cleanups now too and deployed for QA to http://rc.cbl.v1.slate.is/

**Comment by themightychris** [comment]
@jcunn302 this version will be ready to ship once you QA it and Ryon addresses this minor visual regression: https://www.wrike.com/open.htm?id=48894481

**Comment by jcunn302** [comment]
@themightychris I found this issue: https://github.com/SlateFoundation/slate-cbl/issues/41on the latest version.

**Comment by themightychris** [comment]
This release is being cancelled as it contained fatal flaws that didn't make sense to address separately from implementing levels for v0.3.0

**Pull request closed without merging**
