### PR TITLE
Issue/742 vue3 and vuetify

### PR DESCRIPTION
**Pull request by chriscauley**
I have upgraded the code base from vue2 to vue3 and replaced vue-bootstrap with the latest version of beautify. The big remaining question is how much you want me to try to make it match the existing designs. I thought that was more Ryon's domain and am afraid I'll get in the way. 

## Changes

* vue2 > vue3 and vue-bootstrap to vuetify
* Rearranged all the Advanced Portfolio Manager specific code into the vue file.
* Cleaned up the css files a bit.

image

### CODE REVIEW

**Comment by themightychris** [comment]
@chriscauley the close button on the sidebar isn't working

**Comment by themightychris** [comment]
@chriscauley also as you click between cells there seems to be a flash of the sidebar rendering in the bottom-left before getting positioned along the right edge. Is that a style-level issue we should leave for Ryon or something to do with the rendering lifecycle?

**Comment by acouch** [comment]
Noting that @ryon isn't able to jump back in ATM. For right now we are going to move ahead with the functionality and circle back with the CSS at a later time.

**Comment by ryon** [comment]
Updates:

Screenshot 2023-01-31 at 3 10 36 PM

**Comment by themightychris** [comment]
FABULOUS

**Comment by themightychris** [comment]
@chriscauley one regression I just found in this PR that doesn't appear to have been introduced by Ryon's work is that the portfolio progress bar is hardcoded to 50

In this screenshot, the current `develop` branch is on the left and this PR is on the right, same student+competency (ELA, Class of 2020)

Screen Shot 2023-02-02 at 2 05 22 PM

**Pull request merged**
