### PR TITLE
merge v0.3.0 into master

### PR DESCRIPTION
**Pull request by themightychris**
This release supplants v0.2.4 (PR #39) and rolls its rendering pipeline improvements in with the initila implementation of levels and standard overrides

### CODE REVIEW

**Comment by themightychris** [comment]
@ckunkel @jcunn302 this release is ready for QA at http://rc.cbl.v1.slate.is/

Levels and overrides are completely implemented, see [Milestone v0.3.0](https://github.com/SlateFoundation/slate-cbl/milestones/v0.3.0) for remaining issues

**Comment by themightychris** [comment]
@ckunkel this is looking good on my end to merge and release, could you re-check the 3 exports?

**Comment by ckunkel** [comment]
@themightychris I posted a further explanation in https://github.com/SlateFoundation/slate-cbl/commit/08c77efbe32968f7a37f580309601a9245530d3a#commitcomment-13343668 . Only one of the reports functions correctly (competencies).

**Comment by aharley40** [comment]
@themightychris I resolved all the issues we talked about in this issue. https://github.com/SlateFoundation/slate-cbl/commit/4519a34b3fcd94053ee31d16f5499197f88e3c3f

Please check out #49 as well

**Pull request merged**
