### PR TITLE
Cypress automated tests

### PR DESCRIPTION
**Pull request by jtwiest**
- Improve documentation around testing
- Set up smoke screen tests for each Slate sencha app

### CODE REVIEW

**Comment by jtwiest** [comment]
@themightychris Please add some more data when you get a chance.

**Comment by themightychris** [comment]
@jtwiest didn't you have the fixtures repo set up as a submodule?

**Comment by themightychris** [comment]
@nbey could you take this for a spin locally and give the code a review / add notes or commits to smooth out any bumps you hit getting rolling? We need to build out our fixture repo with more CBL data for demo purposes and our basic tests. So far I've been spreading out test cases and sticking to really "neat" test cases (e.g. a stack of 8 ratings and a stack of 10 ratings so the math behind the average is easy to see) -- I'm thinking we stick to that until we start running into needs to test out more exotic scenarios. 

Another thing I've been doing is using some regex find/replace in my code editor to clean up the dumps after creating new data through the UI. I'll null out all the modified columns and set all the created times to the same static value. I might just be being OCD here, but I feel like doing this makes it easier when committing future dumps to spot any accidental extra edits

After I commit a manually cleaned-up set of additions to the fixture dumps, I drop and reload my local copy against that my next dump doesn't register any changes against unedited rows

**Comment by themightychris** [comment]
@jtwiest while you're blocked on that data, could you look into DRYing this up a bit by looking into Cypress's options for sharing utility functions across tests? I'd like to see something like `loginAs('teacher')` and `resetDatabase()` being what we have to repeat

**Comment by themightychris** [comment]
@jtwiest let's also develop a `withExt` helper that lets our tests look something like this:

```javascript
it('View single demonstration rubric as student', () => {

    // open student demonstrations dashboard
    cy.visit('/cbl/dashboards/demonstrations/student');

    cy.myutils.withExt(({ Ext, extQuerySelector, extQuerySelectorAll }) => {

        // get the selector element
        var selectorEl = extQuerySelector('slate-cbl-contentareaselector');

        // ...
    });
});
```

**Review by nbey — COMMENTED** [review]
I updated the URL's in the login test to relative paths, as well as re-ordered the tests to help prevent an error that I was seeing on my machine.

Everything else looks good -- all the tests ran successfully except the wip `teacher_demonstrations`

**Comment by themightychris** [comment]
@nbey is the swapping of the good and bad login tests significant?

**Comment by jtwiest** [comment]
> @jtwiest didn't you have the fixtures repo set up as a submodule?

I was using the downloaded .data directory don't think we got it set up with submodules. The data in there was enough to run the tests Nafis has originally set up as well as I think the first new test I made.

**Pull request merged**
